-- ============================================================================
-- 10_AUTH_TABLES.SQL
-- Centralized authentication and authorization tables for Phase 16.
-- ============================================================================

USE DATABASE HOMECARE_DB;
USE SCHEMA CORE;

-- APP_USER Table
CREATE TABLE IF NOT EXISTS CORE.APP_USER (
  user_id VARCHAR(50) NOT NULL PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  phone VARCHAR(20) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  status VARCHAR(20) DEFAULT 'active', -- 'active', 'suspended', 'pending'
  created_at TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
  updated_at TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

-- ROLE Table
CREATE TABLE IF NOT EXISTS CORE.ROLE (
  role_id VARCHAR(50) NOT NULL PRIMARY KEY,
  role_name VARCHAR(50) UNIQUE NOT NULL,
  description VARCHAR(255),
  created_at TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

-- PERMISSION Table
CREATE TABLE IF NOT EXISTS CORE.PERMISSION (
  permission_id VARCHAR(50) NOT NULL PRIMARY KEY,
  permission_name VARCHAR(50) UNIQUE NOT NULL,
  description VARCHAR(255),
  created_at TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

-- USER_ROLE Table
CREATE TABLE IF NOT EXISTS CORE.USER_ROLE (
  user_role_id VARCHAR(50) NOT NULL PRIMARY KEY,
  user_id VARCHAR(50) NOT NULL REFERENCES CORE.APP_USER(user_id) ON DELETE CASCADE,
  role_id VARCHAR(50) NOT NULL REFERENCES CORE.ROLE(role_id) ON DELETE CASCADE,
  created_at TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

-- ROLE_PERMISSION Table
CREATE TABLE IF NOT EXISTS CORE.ROLE_PERMISSION (
  role_permission_id VARCHAR(50) NOT NULL PRIMARY KEY,
  role_id VARCHAR(50) NOT NULL REFERENCES CORE.ROLE(role_id) ON DELETE CASCADE,
  permission_id VARCHAR(50) NOT NULL REFERENCES CORE.PERMISSION(permission_id) ON DELETE CASCADE,
  created_at TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

-- USER_SESSION Table
CREATE TABLE IF NOT EXISTS CORE.USER_SESSION (
  session_id VARCHAR(50) NOT NULL PRIMARY KEY,
  user_id VARCHAR(50) NOT NULL REFERENCES CORE.APP_USER(user_id) ON DELETE CASCADE,
  token VARCHAR(500) NOT NULL,
  refresh_token VARCHAR(500) NOT NULL,
  expires_at TIMESTAMP_TZ NOT NULL,
  revoked BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

-- PASSWORD_RESET Table
CREATE TABLE IF NOT EXISTS CORE.PASSWORD_RESET (
  reset_id VARCHAR(50) NOT NULL PRIMARY KEY,
  user_id VARCHAR(50) NOT NULL REFERENCES CORE.APP_USER(user_id) ON DELETE CASCADE,
  token VARCHAR(255) NOT NULL,
  expires_at TIMESTAMP_TZ NOT NULL,
  used BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

-- LOGIN_HISTORY Table
CREATE TABLE IF NOT EXISTS CORE.LOGIN_HISTORY (
  history_id VARCHAR(50) NOT NULL PRIMARY KEY,
  user_id VARCHAR(50) REFERENCES CORE.APP_USER(user_id) ON DELETE SET NULL,
  login_at TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
  ip_address VARCHAR(45),
  user_agent VARCHAR(500),
  status VARCHAR(20) NOT NULL, -- 'success', 'failed'
  failure_reason VARCHAR(255)
);
